package com.uib.api.enums;

public enum ResponseCode {
    SUCCESS,
    ERROR,
    FILE_SAVE_SUCCESS,
    FILE_SAVE_ERROR,
    DELETE_SUCCESS,
    USER_ADDED_SUCCESS,
    USER_ADDED_ERROR,
    USER_HAS_REGISTERED,
    FILE_UPDATED,
    VERSION_LIST,
    RESTORE_VERSION_SUCCESS,
    UPLOAD_SUCCESS,
    UPLOAD_ERROR,
    USER_HAS_CREATED,
    USER_HAS_CREATED_ADD_PROJECT
}
